name: built_union_generator
version: 0.3.0
description: >
  Dart sum-types, compatible with built_value.dart
  This library is the dev dependency.
homepage: https://github.com/freedomlayer/built_union.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: '>=1.0.0 <3.0.0'
  built_collection: ^5.0.0
  built_union:
    git:
      url: https://github.com/bt-amal/built_union.dart.git
      path: built_union
  analyzer: '>=4.4.0 <6.0.0'
  source_gen: '>=0.9.0 <2.0.0'
  meta: ^1.3.0

dev_dependencies:
  built_value_generator: ^8.0.5
  build_test: ^2.1.5
  logging: ^1.0.1
  test: ^1.21.4
